apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-finops-automator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/dr-musa-bala/cloud-finOps-Automator.git'
    targetRevision: HEAD
    path: finops-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
