apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleaner
  labels:
    app: finops-automator
    release: kube-prometheus
spec:
  schedule: "{{ .Values.cleaner.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: finops-cleaner
            release: kube-prometheus
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleaner
              image: {{ .Values.cleaner.image }}
              imagePullPolicy: Never
              ports:
                - name: cleaner-metrics
                  containerPort: 8001
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /metrics
                  port: 8001
                initialDelaySeconds: 1
                periodSeconds: 2
              env:
                - name: FLOCI_ENDPOINT
                  value: "{{ .Values.global.flociEndpoint }}"
                - name: AWS_DEFAULT_REGION
                  value: "{{ .Values.global.region }}"
                - name: AWS_ACCESS_KEY_ID
                  value: "{{ .Values.global.awsAccessKeyId }}"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "{{ .Values.global.awsSecretAccessKey }}"